services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: scheduler_app_dev
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
